/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ApplicationSchema extends BaseModel {
  static $columns = [
    'availability',
    'birthDate',
    'city',
    'country',
    'createdAt',
    'educationLevel',
    'email',
    'experienceDescription',
    'experienceYears',
    'fullName',
    'id',
    'motivation',
    'phone',
    'portfolioUrl',
    'priority',
    'program',
    'score',
    'scoreBreakdown',
    'status',
    'updatedAt',
  ] as const
  $columns = ApplicationSchema.$columns
  @column()
  declare availability: string
  @column.date()
  declare birthDate: DateTime | null
  @column()
  declare city: string | null
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare educationLevel: string
  @column()
  declare email: string
  @column()
  declare experienceDescription: string | null
  @column()
  declare experienceYears: number
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare motivation: string
  @column()
  declare phone: string | null
  @column()
  declare portfolioUrl: string | null
  @column()
  declare priority: string
  @column()
  declare program: string
  @column()
  declare score: number
  @column()
  declare scoreBreakdown: any
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OfferSchema extends BaseModel {
  static $columns = [
    'benefits',
    'contractType',
    'createdAt',
    'deadline',
    'educationLevel',
    'id',
    'languages',
    'location',
    'minExperienceYears',
    'missions',
    'niceSkills',
    'profile',
    'publishedAt',
    'requiredSkills',
    'salaryRange',
    'status',
    'summary',
    'title',
    'updatedAt',
    'userId',
    'workMode',
  ] as const
  $columns = OfferSchema.$columns
  @column()
  declare benefits: string | null
  @column()
  declare contractType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare deadline: DateTime | null
  @column()
  declare educationLevel: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare languages: any
  @column()
  declare location: string | null
  @column()
  declare minExperienceYears: number
  @column()
  declare missions: string
  @column()
  declare niceSkills: any
  @column()
  declare profile: string | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare requiredSkills: any
  @column()
  declare salaryRange: string | null
  @column()
  declare status: string
  @column()
  declare summary: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare workMode: string
}

export class UserSchema extends BaseModel {
  static $columns = [
    'companyName',
    'createdAt',
    'email',
    'fullName',
    'id',
    'password',
    'role',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare companyName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
